"""empty message

Revision ID: 4cafcaa5fc45
Revises: 
Create Date: 2021-01-28 11:17:20.351461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cafcaa5fc45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CreditCardNumber', sa.String(length=255), nullable=False),
    sa.Column('CardHolder', sa.String(length=255), nullable=False),
    sa.Column('ExpirationDate', sa.Date(), nullable=False),
    sa.Column('SecurityCode', sa.String(length=3), nullable=True),
    sa.Column('Amount', sa.Float(), nullable=False),
    sa.Column('numberTrials', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Reject', 'To Treat', name='poststatus'), server_default='To Treat', nullable=False),
    sa.Column('payment_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_type_id'], ['paymentType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('paymentType')
    # ### end Alembic commands ###
